### ISSUE TITLE
Fails to compile with Visual Studio 2026 (Flutter 3.39+)

### ISSUE THREAD

**Issue by daltzctr** [chan150/flutter_blue_plus_winrt#2]
1. Create a new flutter app
2. `flutter channel beta`
3. `flutter upgrade`
4. Add `flutter_blue_plus` as a dependency
5. `device.connect`
6. Observe compile error while attempting to build for windows.

`Flutter (Channel beta, 3.40.0-0.2.pre, on Microsoft Windows [Version 10.0.26200.7462], locale en-US)`

```
F:\GitHub\MyTestApp\windows\flutter\ephemeral\.plugin_symlinks\flutter_blue_plus_winrt\windows\flutter_blue_plus_winrt_plugin.cpp(1340,52): error C2220: the following warning is treated as an error [F:\GitHub\MyTestApp\build\windows\x64\plugins\flutter_blue_plus_winrt\flutter_blue_plus_winrt_plugin.vcxproj]
F:\GitHub\MyTestApp\windows\flutter\ephemeral\.plugin_symlinks\flutter_blue_plus_winrt\windows\flutter_blue_plus_winrt_plugin.cpp(1340,52): warning C4864: expected 'template' keyword before dependent template name [F:\GitHub\MyTestApp\build\windows\x64\plugins\flutter_blue_plus_winrt\flutter_blue_plus_winrt_plugin.vcxproj]
F:\GitHub\MyTestApp\windows\flutter\ephemeral\.plugin_symlinks\flutter_blue_plus_winrt\windows\flutter_blue_plus_winrt_plugin.cpp(1386,57): warning C4864: expected 'template' keyword before dependent template name [F:\GitHub\MyTestApp\build\windows\x64\plugins\flutter_blue_plus_winrt\flutter_blue_plus_winrt_plugin.vcxproj]
F:\GitHub\MyTestApp\windows\flutter\ephemeral\.plugin_symlinks\flutter_blue_plus_winrt\windows\flutter_blue_plus_winrt_plugin.cpp(1395,57): warning C4864: expected 'template' keyword before dependent template name [F:\GitHub\MyTestApp\build\windows\x64\plugins\flutter_blue_plus_winrt\flutter_blue_plus_winrt_plugin.vcxproj]
Error: Build process failed.
```

**Comment by christoph-martin** [comment]
Get the same issue
